name: Client Update Notification
on:
  workflow_dispatch:
    inputs:
      client_name:
        description: 'Name of the client being updated'
        required: false
        default: 'Ana Garcia'
        type: string

  push:
    paths:
      - 'axanet_clients_data/**'
jobs:
  notify-team:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Team of Client Update
        run: |
          CLIENT_NAME="${{ github.event.inputs.client_name }}"
          if [ -z "$CLIENT_NAME" ]; then
            CLIENT_NAME="${{ github.event.head_commit.modified[0] }}"
          fi
          if [ -z "$CLIENT_NAME" ]; then
            CLIENT_NAME="${{ github.event.head_commit.added[0] }}"
          fi
          if [ -z "$CLIENT_NAME" ]; then
            CLIENT_NAME="Unknown_Client"
          fi
          CLIENT_NAME=$(basename "$CLIENT_NAME" .txt)
          CLIENT_NAME="${CLIENT_NAME//_/ }"
          echo "CLIENT UPDATED: $CLIENT_NAME"
          echo "Notifying team: ${{ github.actor }}, user1_github, user2_github"
          echo "Timestamp: $(date)"
          echo "Update notification sent successfully!"
