name: Docker Build and Publish

on:
  push:
    branches:
      - main
    # Also build on tags (release tags)
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional image tag (overrides automatic tag)'
        required: false
        default: 'first'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        #if: secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine image name and tags
        id: meta
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/axanet"
          # Prefer explicit tag from workflow_dispatch
          TAG_INPUT="${{ github.event.inputs.tag }}"
          if [ -n "$TAG_INPUT" ]; then
            TAG="$TAG_INPUT"
          else
            # If this run is a tag push, use the tag name (strip refs/tags/)
            if [[ "${{ github.ref }}" == refs/tags/* ]]; then
              TAG="${{ github.ref }}"
              TAG=${TAG#refs/tags/}
            else
              # Use commit short sha and branch name
              SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
              BRANCH=${{ github.ref_name }}
              TAG="${BRANCH}-${SHORT_SHA}"
            fi
          fi
          echo "image=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}
            ${{ steps.meta.outputs.image }}:latest
          platforms: linux/amd64

      - name: Image info
        run: |
          echo "Built image: ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}"
          echo "Triggered by: ${{ github.actor }}"

# Notes:
# - Ensure you add repository secrets: DOCKERHUB_USERNAME and DOCKERHUB_TOKEN
# - The workflow attempts to login only if the secrets exist. Without secrets,
#   build will still run locally on the runner but push will fail.
# - Adjust `IMAGE_NAME` in the `Determine image name and tags` step if you
#   want a different registry or repository (e.g., ghcr.io/${{ github.repository }}).

