name: Improvement Request Notification
on:
  workflow_dispatch:
    inputs:
      request_title:
        description: 'Title of the improvement request'
        required: false
        default: 'Improve logging for client operations'
        type: string
  issues:
    types: [opened, labeled]
jobs:
  notify-team:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Team of Improvement Request
        run: |
          REQUEST_TITLE="${{ github.event.inputs.request_title }}"
          if [ -z "$REQUEST_TITLE" ]; then
            REQUEST_TITLE="${{ github.event.issue.title }}"
          fi
          LABEL_NAME="${{ github.event.label.name }}"
          if [ -n "$LABEL_NAME" ] && [ "$LABEL_NAME" != "improvement" ]; then
            echo "Triggered by label '$LABEL_NAME' (not 'improvement'), skipping notification."
            exit 0
          fi
          if [ -z "$REQUEST_TITLE" ]; then
            REQUEST_TITLE="Unknown Improvement"
          fi
          REQUEST_TITLE="${REQUEST_TITLE//_/ }"
          echo "IMPROVEMENT REQUEST: $REQUEST_TITLE"
          echo "Notifying team: ${{ github.actor }}, user1_github, user2_github"
          echo "Timestamp: $(date)"
          echo "Improvement request logged successfully!"
